### ISSUE TITLE
Password error in console and not working in FF for me

### ISSUE THREAD

**Issue by j2l** [K0IN/Notify#54]
Great idea, congrats!
Using ubuntu 22.04
I set up a testing docker instance with a password on my VPS with my domain name, and get the push messages but only on Chromium and its console raises an error: `[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" class=​"mdc-text-field__input" placeholder label=​"Enter login key" id=​"tf-1" valid=​"true">​…​</input>​`
And even without password (using your demo) Firefox stays mute, no notifications.
I didn't expect the client to be mandated to enter the password, only when calling the API using POST.
Why password is mandatory for client?

Would you please write a little doc about how to implement the browser code within a NodeJS project on another docker instance? Because usually, notifying is useful in an app :)
Also, is there a way to notify only one user?

Thank you!

**Comment by K0IN** [comment]
Hi, 

Thanks for your feedback, I can reproduce the Firefox issue (on Windows), and try to fix it next week. 
Even though chrome raises this error does the notifications work?


The password is needed for the “signup” endpoint to verify that you are able to sign up, since this does only happen when you “enable” the app you will not get prompt before. -> so it shouldn't be mandatory, can you explain a bit further?

I would really like to provide a NodeJs library in the future.
But there are a couple of reasons, why I probably won't: 
1. I'm not a webcrypto/crypto expert (this project uses a lot of crypto under the hood)
2. There are other great libraries that are much more battle tested out there like: [web-push](https://www.npmjs.com/package/web-push) and [pushkit](https://npm.io/package/pushkit)
3. Most of the code is handling UI and User management, these are application sided duties.
4. I Personally don't use NodeJS, but I might at some point publish a sdk/library for Deno.

Currently, there is no way to notify only one user, but this should be an easy extension of the API.

**Comment by K0IN** [comment]
FF issu fixed in https://github.com/K0IN/Notify/pull/55

**Comment by j2l** [comment]
That was quickly fixed! Thank you!

> Even though chrome raises this error does the notifications work?

Yes

I'll dig more for now to better grasp the process.
